name: ruff

on:
  push:
    branches: [main]
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install ruff
      run: |
        python -m pip install --upgrade pip
        pip install ruff
    - run: ruff format --check akinator

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install ruff
      run: |
        python -m pip install --upgrade pip
        pip install ruff
    - run: ruff check akinator